# Generated by Django 4.1.3 on 2022-12-04 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="services",
            name="description",
            field=models.CharField(default="alo", max_length=255),
            preserve_default=False,
        ),
    ]
