# Generated by Django 4.1.3 on 2022-12-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_services_category_services_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="services", name="category",),
    ]
