# Generated by Django 4.1.3 on 2022-12-04 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_services_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="services", name="job_date_time",),
        migrations.AddField(
            model_name="services",
            name="job_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="services",
            name="job_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
