# Generated by Django 4.1.3 on 2022-12-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_remove_services_job_date_time_services_job_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="services", old_name="value", new_name="price",
        ),
    ]
