# Generated by Django 4.1.3 on 2022-12-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_rename_value_services_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services", name="job_date", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="services", name="job_time", field=models.TimeField(null=True),
        ),
    ]
