# Generated by Django 4.1.3 on 2022-12-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_services_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="services", name="description",),
    ]
