# Generated by Django 4.1.3 on 2022-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_remove_services_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="services", name="category",),
        migrations.AddField(
            model_name="services",
            name="description",
            field=models.CharField(default="alo", max_length=255),
            preserve_default=False,
        ),
    ]
