# Generated by Django 4.1.3 on 2022-11-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="author", new_name="autor",),
        migrations.RenameField(
            model_name="post", old_name="body", new_name="conteúdo",
        ),
        migrations.RenameField(model_name="post", old_name="title", new_name="título",),
    ]
