# Generated by Django 4.1.3 on 2022-11-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_author_post_autor_rename_body_post_conteúdo_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="autor", new_name="author",),
        migrations.RenameField(
            model_name="post", old_name="conteúdo", new_name="content",
        ),
        migrations.RenameField(model_name="post", old_name="título", new_name="title",),
    ]
