# Generated by Django 4.1.3 on 2022-11-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_autor_post_author_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="content", new_name="body",),
    ]
