# Generated by Django 4.1.3 on 2022-11-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="date", new_name="datetime",
        ),
    ]
