# Generated by Django 4.1.3 on 2022-11-03 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_date_post_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2022, 11, 2, 23, 30, 53, 796911)
            ),
        ),
    ]
