# Generated by Django 4.1.3 on 2022-11-03 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="imageURL",
            field=models.URLField(
                default="https://www.centralgospelmusic.com.br/noticia/consagracao-do-cd-a-ultima-palavra-758.jpg"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 5, 11, 23, 980617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
