# Generated by Django 4.1.3 on 2022-11-03 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_post_imageurl_alter_post_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 17, 32, 32, 757055, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="imageURL",
            field=models.URLField(
                default="https://www.ncenet.com/wp-content/uploads/2020/04/No-image-found.jpg"
            ),
        ),
    ]
