# Generated by Django 4.1.3 on 2022-11-03 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_post_datetime_alter_post_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 17, 34, 43, 947401, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
