# Generated by Django 4.1.3 on 2022-11-03 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 3, 19, 47, 19, 116509, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
