# Generated by Django 4.1.3 on 2022-11-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_post_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
