# Generated by Django 4.1.3 on 2022-11-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(default="Treino", to="blog.category"),
        ),
    ]
