# Generated by Django 4.1.3 on 2022-11-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255, verbose_name="E-mail"),
        ),
    ]
